page_heading: Tabellen Tippspiel 23/24
points_by_difference:
  0: 3
  1: 2
  2: 1
scrape_targets:
- league_name: 1. Bundesliga
  number_of_teams: 18
  url: 
    https://www.sportschau.de/live-und-ergebnisse/fussball/deutschland-bundesliga/se51884/2023-2024/tabelle
- league_name: 2. Bundesliga
  number_of_teams: 18
  url: 
    https://www.sportschau.de/live-und-ergebnisse/fussball/deutschland-2-bundesliga/se51885/2023-2024/tabelle
tips:
- player_name: Pr
  league_tips:
  - league_name: 1. Bundesliga
    predicted_ranking:
    - Leverkusen 
    - Bayern 
    - BVB
    - Wolfsburg  
    - Leipzig 
    - Hoffenheim
    - Gladbach 
    - Frankfurt  
    - Freiburg 
    - Union
    - Stuttgart 
    - Köln 
    - Mainz 
    - Werder 
    - Augsburg  
    - Heidenheim
    - Darmstadt
    - Bochum
  - league_name: 2. Bundesliga
    predicted_ranking:
    - Hsv
    - Düsseldorf 
    - Schalke 
    - KSC 
    - St. Pauli 
    - Hannover 
    - Fürth 
    - Hertha 
    - Nürnberg
    - Paderborn 
    - Kiel 
    - Magdeburg 
    - Rostock 
    - Lautern
    - Osnabrück 
    - Elversberg 
    - Wiesbaden 
    - Braunschweig
- player_name: Mcl
  league_tips:
  - league_name: 1. Bundesliga
    predicted_ranking:
    - BVB
    - Bayern 
    - Leverkusen
    - Union
    - Leipzig 
    - Werder 
    - Gladbach 
    - Köln
    - Freiburg 
    - Wolfsburg
    - Stuttgart 
    - Frankfurt
    - Mainz 
    - Hoffenheim
    - Bochum
    - Augsburg
    - Darmstadt
    - Heidenheim
  - league_name: 2. Bundesliga
    predicted_ranking:
    - Hsv
    - Düsseldorf 
    - St. Pauli
    - KSC 
    - Osnabrück 
    - Magdeburg 
    - Kiel
    - Lautern
    - Schalke
    - Paderborn 
    - Fürth
    - Nürnberg
    - Rostock 
    - Wiesbaden
    - Hannover
    - Elversberg 
    - Hertha 
    - Braunschweig 
- player_name: Dmk
  league_tips:
  - league_name: 1. Bundesliga
    predicted_ranking:
    - Bayern München
    - Borussia Dortmund
    - RB Leipzig
    - Bayer Leverkusen
    - Union Berlin
    - SC Freiburg
    - Eintracht Frankfurt
    - 1. FC Köln
    - Borussia Mönchengladbach
    - Werder Bremen
    - TSG Hoffenheim
    - VfL Wolfsburg
    - FSV Mainz
    - SV Darmstadt 98
    - FC Augsburg
    - VfL Bochum
    - 1. FC Heidenheim 1846
    - VfB Stuttgart
  - league_name: 2. Bundesliga
    predicted_ranking:
    - Hamburger SV
    - Schalke
    - FC St. Pauli
    - Fortuna Düsseldorf
    - Hannover
    - Karlsruher SC
    - Holstein Kiel
    - Hertha BSC
    - 1. FC Nürnberg
    - SpVgg Greuther Fürth
    - SC Paderborn
    - 1. FC Kaiserslautern
    - SV 07 Elversberg
    - SV Wehen Wiesbaden
    - FC Hansa Rostock
    - Eintracht Braunschweig
    - VfL 1899 Osnabrück
    - FC Magdeburg
- player_name: Ncl
  league_tips:
  - league_name: 1. Bundesliga
    predicted_ranking:
    - Borussia Dortmund
    - Bayer Leverkusen
    - Bayern München
    - RB Leipzig
    - SC Freiburg
    - FC Union Berlin
    - Borussia Mönchengladbach
    - VfL Wolfsburg
    - Eintracht Frankfurt
    - Hoffenheim
    - VfB Stuttgart
    - SV Darmstadt 98
    - FSV Mainz 05
    - FC Köln
    - FC Augsburg
    - Werder Bremen
    - FC Heidenheim 1846
    - VfL Bochum
  - league_name: 2. Bundesliga
    predicted_ranking:
    - Fortuna Düsseldorf
    - Hamburger SV
    - FC Schalke 04
    - FC St Pauli
    - Karlsruher SC
    - SC Paderborn 07
    - FC Magdeburg
    - Hannover 96
    - Holstein Kiel
    - SpVgg Greuther Fürth
    - FC Hansa Rostock
    - FC Nürnberg
    - SV Wehen Wiesbaden
    - Hertha BSC
    - FC Kaiserslautern
    - Eintracht Braunschweig
    - VfL Osnabrück
    - SV 07 Elversberg
- player_name: Brd
  league_tips:
  - league_name: 1. Bundesliga
    predicted_ranking:
    - Bayern München
    - Bayer Leverkusen
    - RB Leipzig
    - Borussia Dortmund
    - FC Union Berlin
    - SC Freiburg
    - Borussia Mönchengladbach
    - Eintracht Frankfurt
    - VfL Wolfsburg
    - VfB Stuttgart
    - FC Köln
    - FSV Mainz 05
    - Hoffenheim
    - Werder Bremen
    - FC Augsburg
    - FC Heidenheim 1846
    - SV Darmstadt 98
    - VfL Bochum
  - league_name: 2. Bundesliga
    predicted_ranking:
    - Hamburger SV
    - Fortuna Düsseldorf
    - Karlsruher SC
    - Hannover 96
    - FC St Pauli
    - FC Schalke 04
    - Holstein Kiel
    - SC Paderborn 07
    - SpVgg Greuther Fürth
    - FC Magdeburg
    - FC Nürnberg
    - FC Hansa Rostock
    - FC Kaiserslautern
    - SV Wehen Wiesbaden
    - Eintracht Braunschweig
    - Hertha BSC
    - VfL Osnabrück
    - SV 07 Elversberg